ShahrChap.Web/Areas/UserPanel/Controllers/AddressController.cs
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShahrChap.Core.DTOs;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Address;

namespace ShahrChap.Web.Areas.UserPanel.Controllers;

[Area("UserPanel")]
[Authorize]
public class AddressController : Controller
{
    private readonly IUserService _userService;
    public AddressController(IUserService userService)
    {
        _userService = userService;
    }

    public IActionResult Index()
    {
        return View(_userService.GetUserAdresses(User.Identity.Name));
    }

    public IActionResult AddAddress()
    {
        ViewBag.UserId = _userService.GetUserIdWithUserName(User.Identity.Name);
        ViewData["Provinces"] = new SelectList(_userService.GetAllProvince(), "ProvinceId", "ProvinceName");

        return View();
    }
    [HttpPost]
    public IActionResult AddAddress(AddressViewModel addAddress)
    {
        int userId = _userService.GetUserIdWithUserName(User.Identity.Name);
        ViewBag.UserId = userId;
        ViewData["Provinces"] = new SelectList(_userService.GetAllProvince(), "ProvinceId", "ProvinceName", addAddress.ProvinceId);
        ViewData["Cities"] = new SelectList(_userService.GetProvincCities(addAddress.ProvinceId), "CityId", "CityName", addAddress.CityId);

        if (!ModelState.IsValid)
            return View(addAddress);

        var address = new UserAddress
        {
            CityId = addAddress.CityId,
            FullAddress = addAddress.FullAddress,
            FullName = addAddress.FullName,
            HouseNumber = addAddress.HouseNumber,
            PostCode = addAddress.PostCode,
            ProvinceId = addAddress.ProvinceId,
            UserId = userId
        };

        //Add Address
        _userService.AddAddress(address);
        return RedirectToAction("Index");
    }

    public IActionResult EditAddress(int Id)
    {
        UserAddress address = _userService.GetUserAddressWithAddressId(Id);
        if (address == null)
        {
            return NotFound();
        }

        int userId = _userService.GetUserIdWithUserName(User.Identity.Name);
        ViewBag.UserId = userId;
        ViewData["Provinces"] = new SelectList(_userService.GetAllProvince(), "ProvinceId", "ProvinceName", address.ProvinceId);
        ViewData["Cities"] = new SelectList(_userService.GetProvincCities(address.ProvinceId), "CityId", "CityName", address.CityId);

        var userAddress = new AddressViewModel
        {
            CityId = address.CityId,
            FullAddress = address.FullAddress,
            FullName = address.FullName,
            HouseNumber = address.HouseNumber,
            PostCode = address.PostCode,
            ProvinceId = address.ProvinceId,
            UserId = userId,
            UserAddressId = address.UserAddressId
        };

        return View(userAddress);
    }
    [HttpPost]
    public IActionResult EditAddress(int addressId, AddressViewModel editAddress)
    {
        int userId = _userService.GetUserIdWithUserName(User.Identity.Name);
        ViewBag.UserId = userId;
        ViewData["Provinces"] = new SelectList(_userService.GetAllProvince(), "ProvinceId", "ProvinceName", editAddress.ProvinceId);
        ViewData["Cities"] = new SelectList(_userService.GetProvincCities(editAddress.ProvinceId), "CityId", "CityName", editAddress.CityId);

        if (!ModelState.IsValid)
            return View();

        var address = new UserAddress
        {
            UserAddressId = editAddress.UserAddressId,
            CityId = editAddress.CityId,
            FullAddress = editAddress.FullAddress,
            FullName = editAddress.FullName,
            HouseNumber = editAddress.HouseNumber,
            PostCode = editAddress.PostCode,
            ProvinceId = editAddress.ProvinceId,
            UserId = userId
        };
        _userService.UpdateAddress(address);
        return RedirectToAction("Index");
    }

    public IActionResult DeleteAddress(int Id)
    {
        UserAddress address = _userService.GetUserAddressWithAddressId(Id);
        if (address == null)
        {
            return NotFound();
        }

        _userService.DeleteAddress(address);

        return Json(new { success = true, message = "حذف با موفقیت انجام شد" });
    }
    // AJAX method to get cities based on selected province
    public JsonResult GetCities(int provinceId)
    {
        var cities = _userService.GetProvincCities(provinceId).Select(c => new { c.CityId, c.CityName }).ToList();
        return Json(cities);
    }
}

ShahrChap.Web/Areas/UserPanel/Views/Address/AddAddress.cshtml
@model ShahrChap.Core.DTOs.AddressViewModel

@{
    ViewBag.Title = "افزودن آدرس";
}
<section class="container internal-style pt-3">
    <ol class="breadcrumb drop-shadow">
        <li class="breadcrumb-item"><a href="/">خانه</a></li>
        <li class="breadcrumb-item"><a href="/UserPanel/Address">دفترچه آدرس</a></li>
        <li class="breadcrumb-item active" aria-current="page">افزودن آدرس</li>
    </ol>
</section>

<section class="container">
    <div class="user-account">
        <div class="row">
            <partial name="_SideBar" />
            <div class="col-md-9 col-sm-8 col-xs-12">
                <section class="user-account-content  drop-shadow">
                    <header>
                        <h1> افزودن آدرس </h1>
                    </header>
                    <div class="inner">
                        <div class="account-information">
                            <form asp-action="AddAddress">
                                <input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />
                                <div class="row">
                                    <div class="col-md-12 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-user"></i>
                                            <input type="text" asp-for="FullName" class="form-control" placeholder="نام و نام خانوادگی">
                                        </div>
                                        <span class="txt-red" asp-validation-for="FullName"></span>
                                    </div>
                                    <div class="col-md-12 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-directions"></i>
                                            <textarea type="text" asp-for="FullAddress" class="form-control" placeholder="آدرس کامل">
                                            </textarea>
                                        </div>
                                        <span class="txt-red" asp-validation-for="FullAddress"></span>
                                    </div>
                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group select-container">
                                            <i class="icon uil uil-location-point me-2"></i>
                                            <div class="select-wrapper">
                                                <select asp-for="ProvinceId" asp-items="ViewBag.Provinces" class="form-control" placeholder="استان" id="province-dropdown">
                                                    <option value="">استان</option>
                                                </select>
                                                <i id="dropdownIcon" class="icon uil uil-angle-down"></i>
                                            </div>
                                        </div>
                                        <span class="txt-red" asp-validation-for="ProvinceId"></span>
                                    </div><div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group select-container">
                                            <i class="icon uil uil-location-point me-2"></i>
                                            <div class="select-wrapper">
                                                <select asp-for="CityId" asp-items="ViewBag.Cities" class="form-control" placeholder="شهر" id="city-dropdown">
                                                    <option value="">شهر</option>
                                                </select>
                                                <i id="dropdownIcon" class="icon uil uil-angle-down"></i>
                                            </div>
                                        </div>
                                        <span class="txt-red" asp-validation-for="CityId"></span>
                                    </div>

                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-estate"></i>
                                            <input type="text" asp-for="PostCode" class="form-control" placeholder="کد پستی">
                                        </div>
                                        <span class="txt-red" asp-validation-for="PostCode"></span>
                                    </div>
                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-sign-left"></i>
                                            <input type="text" asp-for="HouseNumber" class="form-control" placeholder="پلاک">
                                        </div>
                                        <span class="txt-red" asp-validation-for="HouseNumber"></span>
                                    </div>
                                    @if (ViewBag.Errors != null)
                                    {
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach (var error in ViewBag.Errors)
                                                {
                                                    <li style="color:red">@error</li>
                                                }
                                            </ul>
                                        </div>
                                    }
                                    <div class="mt-3">
                                        <button class="btn btn-blue">
                                            <i class="uil uil-location-arrow"></i>
                                            افزودن آدرس
                                        </button>

                                        <a asp-action="Index" class="btn"><i class="uil uil-arrow-right"></i> بازگشت</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#province-dropdown").change(function () {
                var provinceId = $(this).val();
                $.ajax({
                    type: "post",
                    url: "/UserPanel/GetCityList?provinceId=" + provinceId,
                    contentType: "html",
                    success: function (result) {
                        debugger
                        $("#City").empty();
                        $("#City").append(result);
                    }
                })
            })
        })

        $(document).ready(function () {
            $('#province-dropdown').change(function () {
                var provinceId = $(this).val();
                $.getJSON('/UserPanel/Address/GetCities', { provinceId: provinceId }, function (data) {
                    console.log('url is ok');
                    var items = '';
                    $('#city-dropdown').empty();
                    items += "<option> شهر </option>";
                    $.each(data, function (i, city) {
                        items += "<option value='" + city.cityId + "'>" + city.cityName + "</option>";
                    });
                    $('#city-dropdown').html(items);
                });
            });
        });
    </script>
}

ShahrChap.Web/Areas/UserPanel/Views/Address/EditAddress.cshtml
@model ShahrChap.Core.DTOs.AddressViewModel

@{
    ViewBag.Title = "ویرایش آدرس";
}
<section class="container internal-style pt-3">
    <ol class="breadcrumb drop-shadow">
        <li class="breadcrumb-item"><a href="/">خانه</a></li>
        <li class="breadcrumb-item"><a href="/UserPanel/Address">دفترچه آدرس</a></li>
        <li class="breadcrumb-item active" aria-current="page">ویرایش آدرس</li>
    </ol>
</section>

<section class="container">
    <div class="user-account">
        <div class="row">
            <partial name="_SideBar" />
            <div class="col-md-9 col-sm-8 col-xs-12">
                <section class="user-account-content  drop-shadow">
                    <header>
                        <h1> ویرایش آدرس </h1>
                    </header>
                    <div class="inner">
                        <div class="account-information">
                            <form asp-action="EditAddress">
                                <input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />
                                <input type="hidden" asp-for="UserAddressId"/>
                                <div class="row">
                                    <div class="col-md-12 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-user"></i>
                                            <input type="text" asp-for="FullName" class="form-control" placeholder="نام و نام خانوادگی">
                                        </div>
                                        <span class="txt-red" asp-validation-for="FullName"></span>
                                    </div>
                                    <div class="col-md-12 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-directions"></i>
                                            <textarea type="text" asp-for="FullAddress" class="form-control" placeholder="آدرس کامل">
                                            </textarea>
                                        </div>
                                        <span class="txt-red" asp-validation-for="FullAddress"></span>
                                    </div>
                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group select-container">
                                            <i class="icon uil uil-location-point me-2"></i>
                                            <div class="select-wrapper">
                                                <select asp-for="ProvinceId" asp-items="ViewBag.Provinces" class="form-control" placeholder="استان" id="province-dropdown">
                                                    <option value="">استان</option>
                                                </select>
                                                <i id="dropdownIcon" class="icon uil uil-angle-down"></i>
                                            </div>
                                        </div>
                                        <span class="txt-red" asp-validation-for="ProvinceId"></span>
                                    </div><div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group select-container">
                                            <i class="icon uil uil-location-point me-2"></i>
                                            <div class="select-wrapper">
                                                <select asp-for="CityId" asp-items="ViewBag.Cities" class="form-control" placeholder="شهر" id="city-dropdown">
                                                    <option value="">شهر</option>
                                                </select>
                                                <i id="dropdownIcon" class="icon uil uil-angle-down"></i>
                                            </div>
                                        </div>
                                        <span class="txt-red" asp-validation-for="CityId"></span>
                                    </div>

                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-estate"></i>
                                            <input type="text" asp-for="PostCode" class="form-control" placeholder="کد پستی">
                                        </div>
                                        <span class="txt-red" asp-validation-for="PostCode"></span>
                                    </div>
                                    <div class="col-md-6 col-sm-10 col-xs-12">
                                        <div class="input-group">
                                            <i class="icon uil uil-sign-left"></i>
                                            <input type="text" asp-for="HouseNumber" class="form-control" placeholder="پلاک">
                                        </div>
                                        <span class="txt-red" asp-validation-for="HouseNumber"></span>
                                    </div>
                                    <div class="mt-3">
                                        <button class="btn btn-blue">
                                            <i class="uil uil-location-arrow"></i>
                                            ثبت تغییرات
                                        </button>

                                        <a asp-action="Index" class="btn"><i class="uil uil-arrow-right"></i> بازگشت</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#province-dropdown").change(function () {
                var provinceId = $(this).val();
                $.ajax({
                    type: "post",
                    url: "/UserPanel/GetCityList?provinceId=" + provinceId,
                    contentType: "html",
                    success: function (result) {
                        debugger
                        $("#City").empty();
                        $("#City").append(result);
                    }
                })
            })
        })

        $(document).ready(function () {
            $('#province-dropdown').change(function () {
                var provinceId = $(this).val();
                $.getJSON('/UserPanel/Address/GetCities', { provinceId: provinceId }, function (data) {
                    console.log('url is ok');
                    var items = '';
                    $('#city-dropdown').empty();
                    items += "<option> شهر </option>";
                    $.each(data, function (i, city) {
                        items += "<option value='" + city.cityId + "'>" + city.cityName + "</option>";
                    });
                    $('#city-dropdown').html(items);
                });
            });
        });
    </script>
}

ShahrChap.Web/Areas/UserPanel/Views/Address/Index.cshtml
@model IEnumerable<ShahrChap.Core.DTOs.ShowAddressViewModel>
@{
    ViewData["Title"] = "دفترچه آدرس";
}

<section class="container internal-style pt-3">
    <ol class="breadcrumb drop-shadow">
        <li class="breadcrumb-item"><a href="/">خانه</a></li>
        <li class="breadcrumb-item active" aria-current="page">دفترچه آدرس</li>
    </ol>
</section>

<section class="container">
    <div class="user-account">
        <div class="row">
            <partial name="_SideBar" />
            <div class="col-md-9 col-sm-8 col-xs-12">
                <section class="user-account-content  drop-shadow">
                    <header>
                        <h1> آدرس ها </h1>
                    </header>
                    <div class="inner">
                        <div class="account-information">
                            @if (Model.Any())
                            {
                                @foreach (var item in Model)
                                {
                                    <ul>
                                        <li> <i class="uil uil-user"></i> نام و نام خانوادگی : @item.FullName </li>
                                        <li>
                                            <i class="uil uil-map"></i> @item.FullAddress
                                        </li>
                                        <li>
                                            <i class="uil uil-location-pin-alt"></i> @item.Province - @item.City
                                        </li>
                                        <li> <i class="uil uil-estate"></i> @item.PostCode - پلاک @item.HouseNumber </li>
                                    </ul>
                                    <a asp-action="EditAddress" asp-route-id="@item.AddressId" class="btn btn-sm btn-outline-blue">
                                        <i class="uil uil-edit"></i>
                                    </a>
                                    @* Assuming you have a model with an "Id" property *@

                                    <td>
                                    </td>

                                    <a href="#" onclick="confirmDelete('@Url.Action("DeleteAddress", "Address", new { Id = item.AddressId })')" class="btn btn-sm btn-red"><i class="uil uil-trash-alt"></i></a>
                                    <hr />
                                }
                            }

                        </div>
                        <a asp-action="AddAddress" class="btn btn-blue"><i class="uil uil-map-marker-plus"></i> افزودن آدرس</a>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>

<script>
    function confirmDelete(url) {
        Swal.fire({
            title: 'آیا از حذف مطمئن هستید؟',
            icon: 'warning',
            showCancelButton: true,

            confirmButtonColor: '#f25f5c',
            cancelButtonColor: '#2a87bb',
            confirmButtonText: 'حذف',
            cancelButtonText: 'لغو'
        }).then((result) => {
            if (result.isConfirmed) {
                // Send AJAX request to the delete action
                $.ajax({
                    type: 'POST', // Use DELETE for deletion
                    url: url,  // Replace with your actual delete URL
                    success: function (data) {
                        if (data.success) {
                            Swal.fire(
                                'حذف شد!',
                                'آدرس مورد نظر با موفقیت حذف شد',
                                'success'
                            ).then(() => {
                                // Reload the page after the success alert is closed
                                location.reload();
                            });
                            // Optionally, reload the page or update the UI
                        } else {
                            Swal.fire(
                                'خطا!',
                                'حذف آدرس مورد نظر با خطا مواجه شد',
                                'error'
                            );
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.error(textStatus, errorThrown);
                        Swal.fire(
                            'خطا!',
                            'خطایی رخ داد',
                            'error'
                        );
                    }
                });
            }
        });
    }
</script>
@section Scripts {
    <script src="~/lib/sweetalert2/dist/sweetalert2.min.js"></script>
    <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css" />
}