ShahrChap.Web/Pages/Admin/Products/AddProductFeatures.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;
using ShahrChap.Core.Services;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;
using System.Diagnostics;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class AddProductFeaturesModel : PageModel
    {
        private IProductService _productService;
        public AddProductFeaturesModel(IProductService productService)
        {
            _productService = productService;
        }
        public Product CurrentProduct { get; set; }
        public List<Feature> Features { get; set; }

        public void OnGet(int id)
        {
            //GET THE SELECTED FEATURES FOR THIS PRODUCT AND CHECKED IN THE VIEW
            CurrentProduct = _productService.GetProductById(id);
            Features = _productService.GetAllFeatures();
            ViewData["SelectedFeatures"] = _productService.ProductFeatureIds(id);
        }

        public IActionResult OnPost(int ProductId, List<int> SelectedFeature)
        {
            CurrentProduct = _productService.GetProductById(ProductId);
            Features = _productService.GetAllFeatures();
            List<int> existingFeatureIds = _productService.ProductFeatureIds(ProductId);
            ViewData["SelectedFeatures"] = existingFeatureIds;

            Features = _productService.GetAllFeatures();

            if (!ModelState.IsValid)
                return Page();

            if (!existingFeatureIds.OrderBy(x => x).SequenceEqual(SelectedFeature.OrderBy(x => x)))
            {
                //Add Features to product with product id
                _productService.UpdateFeaturesProduct(ProductId, SelectedFeature);
            }
            return RedirectToPage("Index");
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/AddProductService.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class AddProductServiceModel : PageModel
    {
        private IProductService _productService;
        public AddProductServiceModel(IProductService productService)
        {
            _productService = productService;
        }
        [BindProperty(SupportsGet = true)]
        public int ProductId { get; set; }
        public List<Service> ProductServices { get; set; }
        [BindProperty]
        public Service Service { get; set; }
        public void OnGet(int id)
        {
            ProductId = id;
            ViewData["ProductTitle"] = _productService.GetProductById(id).ProductTitle;
            ProductServices = _productService.GetProductServices(id);
        }

        public IActionResult OnPostCreateService()
        {
            ProductId = Service.ProductId;
            ViewData["ProductTitle"] = _productService.GetProductById(ProductId).ProductTitle;
            ProductServices = _productService.GetProductServices(ProductId);

            //Model state check
            if (!ModelState.IsValid)
                return Page();

            if (!string.IsNullOrWhiteSpace(Service.ServiceTitle))
            {
                //Service.ProductId = ProductId;
                Service.IsDelete = false;
                _productService.CreateService(Service);
            }
            return RedirectToPage(new {ProductId});
        }
        
        public IActionResult OnPostDeleteService(int serviceId)
        {
            Service service = _productService.GetServiceById(serviceId);
            ProductId = service.ProductId;
            if (service != null)
            {
                _productService.DeleteService(service);
            }

            return RedirectToPage(new { ProductId });
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/AddSubProductFeatures.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class AddSubProductFeaturesModel : PageModel
    {
        private IProductService _productService;
        public AddSubProductFeaturesModel(IProductService productService)
        {
            _productService = productService;
        }
        public Product CurrentProduct { get; set; }
        public List<ProductFeature> ProductFeatures { get; set; }
        public List<FeatureValue> Values { get; set; }

        //Update product price models
        public List<ProductPrice> ProductPrices { get; set; }
        public List<string> FeatureCombinations { get; set; }
        public void OnGet(int id)
        {
            CurrentProduct = _productService.GetProductById(id);
            ProductFeatures = _productService.GetProductFeatures(CurrentProduct.ParentId.Value);
            Values = _productService.GetAllFeatureValues(CurrentProduct.ParentId.Value);
            ViewData["SelectedFeatureValues"] = _productService.SubProductFeatureValueIds(id);
        }

        public IActionResult OnPost(int ProductId, List<int> SelectedFeatureValue)
        {
            CurrentProduct = _productService.GetProductById(ProductId);

            ProductFeatures = _productService.GetProductFeatures(CurrentProduct.ParentId.Value);
            List<int> existingFeatureValueIds = _productService.SubProductFeatureValueIds(ProductId);
            ViewData["SelectedFeatureValues"] = existingFeatureValueIds;

            Values = _productService.GetAllFeatureValues(CurrentProduct.ParentId.Value);

            if (!ModelState.IsValid)
                return Page();

            //Check if any changes have made to the features
            if (!existingFeatureValueIds.OrderBy(x => x).SequenceEqual(SelectedFeatureValue.OrderBy(x => x)))
            {
                //Add Features to product with product id
                _productService.UpdateFeatureValuesProduct(ProductId, SelectedFeatureValue);
                
                // Add|Update Combintaions in Product Price table
                FeatureCombinations = _productService.GetFeatureCombinations(ProductId);

                ProductPrices = FeatureCombinations.Select(combination => new ProductPrice
                {
                    Combination = combination,
                    Price = 0
                }).ToList();

                //Update the exsiting product prices 
                _productService.AddProductPrices(ProductId, ProductPrices);
            }

            return RedirectToPage("IndexSubProduct", new { id = CurrentProduct.ParentId });
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/CreateProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class CreateProductModel : PageModel
    {
        private IProductService _productService;
        public CreateProductModel(IProductService productService)
        {
            _productService = productService;
        }
        [BindProperty]
        public Product Product { get; set; }
        public void OnGet()
        {
            var groups = _productService.GetGroupForManageProducts();
            var types = _productService.GetTypes();
            ViewData["Groups"] = new SelectList(groups, "Value", "Text");
            ViewData["Types"] = new SelectList(types, "Value", "Text");
        }
        //Change the view page default image location
        public IActionResult OnPost(IFormFile? imgProduct)
        {
            if (!ModelState.IsValid)
            {
                var groups = _productService.GetGroupForManageProducts();
                var types = _productService.GetTypes();
                ViewData["Groups"] = new SelectList(groups, "Value", "Text");
                ViewData["Types"] = new SelectList(types, "Value", "Text");


                return Page();
            }

            _productService.AddProudct(Product, imgProduct);

            return RedirectToPage("Index");
        }
        public JsonResult OnGetJson(int id)
        {
            var subGroup = _productService.GetSubGroupForManageProducts(id);
            SelectList list = new SelectList(subGroup, "Value", "Text");
            return new JsonResult(list);
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/CreateSubProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class CreateSubProductModel : PageModel
    {
        private IProductService _productService;
        public CreateSubProductModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public Product SubProduct { get; set; }
        public Product Parent {  get; set; }
        public void OnGet(int id)
        {
            SubProduct = new Product();
            Parent = _productService.GetProductById(id);
            if (Parent.SubGroupId != null)
            {
                var groups = _productService.GetSubGroupForManageProducts(Parent.SubGroupId.Value);
                ViewData["Groups"] = new SelectList(groups, "Value", "Text");
            }
            else
            {
                SubProduct.GroupId = Parent.GroupId;
            }

            SubProduct.ParentId = id;

        }
        public IActionResult OnPost(IFormFile? imgProduct)
        {
            Parent = _productService.GetProductById((int)SubProduct.ParentId);
            if (!ModelState.IsValid)
            {
                var groups = _productService.GetSubGroupForManageProducts(Parent.SubGroupId.Value);
                ViewData["Groups"] = new SelectList(groups, "Value", "Text");

                return Page();
            }

            SubProduct.ProductTypeId = Parent.ProductTypeId;

            _productService.AddProudct(SubProduct, imgProduct);

            return RedirectToPage("IndexSubProduct", new { id = SubProduct.ParentId });
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/DeleteProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShahrChap.Core.Convertors;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class DeleteProductModel : PageModel
    {
        private IProductService _productService;
        public DeleteProductModel(IProductService productService)
        {
            _productService = productService;
        }
        [BindProperty]
        public Product Product { get; set; }
        public void OnGet(int id)
        {
            Product = _productService.GetProductById(id);
        }

        public IActionResult OnPost()
        {
            Product = _productService.GetProductById(Product.ProductId);
            _productService.DeleteProduct(Product);
            if(Product.ParentId != null)
            {
                return RedirectToPage("IndexSubProduct", new { id = Product.ParentId });
            }
            return RedirectToPage("Index");
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/EditProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class EditProductModel : PageModel
    {
        private IProductService _productService;
        public EditProductModel(IProductService productService)
        {
            _productService = productService;
        }
        [BindProperty]
        public Product Product { get; set; }
        public void OnGet(int id)
        {
            Product = _productService.GetProductById(id);
            var groups = _productService.GetGroupForManageProducts();
            var types = _productService.GetTypes();

            ViewData["Groups"] = new SelectList(groups, "Value", "Text", Product.GroupId);
            ViewData["Types"] = new SelectList(types, "Value", "Text", Product.ProductTypeId);

            var subGroups = _productService.GetSubGroupForManageProducts(Product.GroupId);
            ViewData["SubGroups"] = new SelectList(subGroups, "Value", "Text", Product.SubGroupId);

        }

        public IActionResult OnPost(IFormFile? imgProduct)
        {
            if (!ModelState.IsValid)
            {
                Product = _productService.GetProductById(Product.ProductId);
                var groups = _productService.GetGroupForManageProducts();
                var types = _productService.GetTypes();

                ViewData["Groups"] = new SelectList(groups, "Value", "Text", Product.GroupId);
                ViewData["Types"] = new SelectList(types, "Value", "Text", Product.ProductTypeId);

                var subGroups = _productService.GetSubGroupForManageProducts(Product.GroupId);
                ViewData["SubGroups"] = new SelectList(groups, "Value", "Text", Product.SubGroupId);
                return Page();
            }

            _productService.UpdateProduct(Product, imgProduct);
            //_productService.UpdateFormsOnEditProduct(Product.ProductId);

            return RedirectToPage("Index");
        }

        public JsonResult OnGetJson(int id)
        {
            var subGroup = _productService.GetSubGroupForManageProducts(id);
            SelectList list = new SelectList(subGroup, "Value", "Text");
            return new JsonResult(list);
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/EditSubProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class EditSubProductModel : PageModel
    {
        private IProductService _productService;
        public EditSubProductModel(IProductService productService)
        {
            _productService = productService;
        }
        [BindProperty]
        public Product SubProduct { get; set; }
        public Product Parent { get; set; }
        public void OnGet(int id)
        {
            SubProduct = _productService.GetProductById(id);
            Parent = _productService.GetProductById((int)SubProduct.ParentId);

            if (Parent.SubGroupId != null)
            {
                var groups = _productService.GetSubGroupForManageProducts(Parent.SubGroupId.Value);
                ViewData["Groups"] = new SelectList(groups, "Value", "Text", SubProduct.SubGroupId);
            }
            else
            {
                SubProduct.GroupId = Parent.GroupId;
            }

        }

        public IActionResult OnPost(IFormFile? imgProduct)
        {
            Parent = _productService.GetProductById((int)SubProduct.ParentId);

            if (!ModelState.IsValid)
            {
                if (Parent.SubGroupId != null)
                {
                    var groups = _productService.GetSubGroupForManageProducts(Parent.SubGroupId.Value);
                    ViewData["Groups"] = new SelectList(groups, "Value", "Text", SubProduct.GroupId);
                }
                else
                {
                    SubProduct.GroupId = Parent.GroupId;
                }

                return Page();
            }

            SubProduct.ProductTypeId = Parent.ProductTypeId;

            _productService.UpdateProduct(SubProduct, imgProduct);

            return RedirectToPage("IndexSubProduct", new { id = SubProduct.ParentId });
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShahrChap.Core.DTOs.Products;
using ShahrChap.Core.Services.Interfaces;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class IndexModel : PageModel
    {
        private IProductService _productService;
        public IndexModel(IProductService productService)
        {
            _productService = productService;
        }
        public List<ShowProductForAdminViewModel> ProductList { get; set; }
        public void OnGet()
        {
            ProductList = _productService.GetProductsForAdmin();
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/IndexSubProduct.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShahrChap.Core.DTOs.Products;
using ShahrChap.Core.Services.Interfaces;
using ShahrChap.DataLayer.Entities.Product;

namespace ShahrChap.Web.Pages.Admin.Products
{
    public class IndexSubProductModel : PageModel
    {
        private IProductService _productService;
        public IndexSubProductModel(IProductService productService)
        {
            _productService = productService;
        }
        public List<ShowProductForAdminViewModel> SubProducts { get; set; }
        public Product Product { get; set; }
        public void OnGet(int id)
        {
            ViewData["ProductId"] = id;
            Product = _productService.GetProductById(id);
            SubProducts = _productService.GetSubProductForAdmin(id);
        }
    }
}

ShahrChap.Web/Pages/Admin/Products/AddProductFeatures.cshtml
@page "{id}"
@model ShahrChap.Web.Pages.Admin.Products.AddProductFeaturesModel
@{
    ViewData["Title"] = "- افزودن ویژگی‌ها";
    List<int> SelectedFeatures = ViewData["SelectedFeatures"] as List<int>;
}
<div class="row mb-2">
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/Admin"><i class="uil uil-estate"></i> صفحه نخست</a></li>
            <li class="breadcrumb-item"><a href="/Admin/Products"><i class="uil uil-list-ul"></i> لیست محصولات</a></li>
            <li class="breadcrumb-item active text-success"><i class="uil uil-plus-circle"></i>افزودن ویژگی به @Model.CurrentProduct.ProductTitle</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <input type="hidden" name="ProductId" value="@Model.CurrentProduct.ProductId" />
            <div class="col-md-9">
                <div class="panel panel-primary">
                    <div class="panel-heading">افزودن ویژگی به @Model.CurrentProduct.ProductTitle</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <ul class="feature-list mt-3">
                                @foreach (var feature in Model.Features)
                                {
                                    <li id="featureItem_@feature.FeatureId">
                                        <input type="checkbox" @((SelectedFeatures.Any(p => p == feature.FeatureId) ? "checked" : "")) name="SelectedFeature" id="Feature_@feature.FeatureId" value="@feature.FeatureId">
                                        <label for="Feature_@feature.FeatureId">@feature.FeatureTitle</label>
                                    </li>

                                }
                            </ul>
                        </div>
                        <a href="/Admin/Products" class="btn btn-default">
                            <i class="uil uil-angle-right"></i> بازگشت
                        </a>
                        <button type="submit" class="btn btn-success"><i class="uil uil-plus-circle"></i> افزودن</button>
                    </div>
                </div>
            </div>
            <hr />
        </form>
    </div>
</div>

ShahrChap.Web/Pages/Admin/Products/AddProductService.cshtml
@page "{id}"
@model ShahrChap.Web.Pages.Admin.Products.AddProductServiceModel
@{
    ViewData["Title"] = "- خدمات پس از چاپ";
    var productTitle = ViewData["ProductTitle"];
}
<div class="row mb-2">
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/Admin"><i class="uil uil-estate"></i> صفحه نخست</a></li>
            <li class="breadcrumb-item"><a href="/Admin/Products"><i class="uil uil-list-ul"></i> لیست محصولات</a></li>
            <li class="breadcrumb-item active text-success"><i class="uil uil-brightness-plus"></i> خدمات پس از چاپ @productTitle</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <form method="post">
            @* TODO: CHECK THE PRODUCT ID TO NOT BE 0 *@
            <input type="hidden" asp-for="Service.ProductId" value="@Model.ProductId" />
            <div class="col-md-9">
                <div class="panel panel-primary">
                    <div class="panel-heading">افزودن خدمت جدید به @productTitle</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label>عنوان خدمت</label>
                            <input type="text" asp-for="Service.ServiceTitle" class="form-control">
                            <span asp-validation-for="Service.ServiceTitle"></span>
                        </div>
                        <a href="/Admin/Products" class="btn btn-default">
                            <i class="uil uil-angle-right"></i> بازگشت
                        </a>
                        <button type="submit" asp-page-handler="CreateService" class="btn btn-success"><i class="uil uil-plus-circle"></i> ثبت خدمت</button>
                    </div>
                </div>
            </div>
        </form>
        <hr />
        <table class="table table-striped table-bordered table-hover dataTable no-footer table-text-center" id="dataTables-example" aria-describedby="dataTables-example_info">
            <thead>
                <tr>
                    <td>عنوان ویژگی</td>
                    <td>دستورات</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ProductServices)
                {
                    <tr>
                        <td>@item.ServiceTitle</td>
                        <td>
                            @* <a asp-page-handler="EditService" asp-route-id="@item.ServiceId" class="btn btn-sm btn-warning"><i class="uil uil-edit"></i></a> *@
                            <form method="post" id="deleteForm" asp-page-handler="DeleteService">
                                <input type="hidden" name="productId" value="@Model.ProductId" />
                                <input type="hidden" name="serviceId" value="@item.ServiceId" />
                                <button type="submit" class="btn btn-sm btn-danger" onclick="confirmDelete()">
                                    <i class="uil uil-trash-alt"></i>
                                </button>
                            </form>
                            @* <a asp-page-handler="DeleteService" onclick="return confirm('آیا مطمئن هستید؟');" asp-route-id="@item.ProductId" asp-route-serviceid="@item.ServiceId" class="btn btn-sm btn-danger"><i class="uil uil-trash-alt"></i></a> *@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    function confirmDelete() {
        if (confirm("آیا از حذف این خدمت مطمئن هستید؟")) {
            document.getElementById("deleteForm").submit();
        }
    }
</script>

ShahrChap.Web/Pages/Admin/Products/AddSubProductFeatures.cshtml
@page "{id}"
@model ShahrChap.Web.Pages.Admin.Products.AddSubProductFeaturesModel
@{
    ViewData["Title"] = "- افزودن ویژگی‌ها";
    List<int> SelectedValues = ViewData["SelectedFeatureValues"] as List<int>;
}
<div class="row mb-2">
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/Admin"><i class="uil uil-estate"></i> صفحه نخست</a></li>
            <li class="breadcrumb-item"><a href="/Admin/Products"><i class="uil uil-list-ul"></i> لیست محصولات</a></li>
            <li class="breadcrumb-item"><a href="/Admin/Products/IndexSubProducts/@Model.CurrentProduct.ProductId"><i class="uil uil-sort-amount-down"></i> لیست زیر محصولات</a></li>
            <li class="breadcrumb-item active text-success"><i class="uil uil-plus-circle"></i>افزودن ویژگی به @Model.CurrentProduct.ProductTitle</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <input type="hidden" name="ProductId" value="@Model.CurrentProduct.ProductId" />
            <div class="col-md-9">
                <div class="panel panel-primary">
                    <div class="panel-heading">افزودن ویژگی به @Model.CurrentProduct.ProductTitle</div>
                    <div class="panel-body">
                        <div class="form-group">
                            @foreach (var feature in Model.ProductFeatures)
                            {
                                <label>@feature.Feature.FeatureTitle:</label>
                                <ul class="feature-list mt-3">
                                    @* بر اساس فیچر ها لیست بندی شود و مرتب شود  *@
                                    @foreach (var value in feature.Feature.FeatureValues)
                                    {
                                        <li id="valueItem_@value.FeatureValueId">
                                            <input type="checkbox" @((SelectedValues.Any(p => p == value.FeatureValueId) ? "checked" : "")) name="SelectedFeatureValue" id="Value_@value.FeatureValueId" value="@value.FeatureValueId">
                                            <label for="Value_@value.FeatureValueId">@value.ValueTitle</label>
                                        </li>

                                    }
                                </ul>
                            }
                            
                        </div>
                        <a href="/Admin/Products/IndexSubProduct/@Model.CurrentProduct.ParentId" class="btn btn-default">
                            <i class="uil uil-angle-right"></i> بازگشت
                        </a>
                        <button type="submit" class="btn btn-success"><i class="uil uil-plus-circle"></i> افزودن</button>

                    </div>
                </div>
            </div>
            <hr />
            <div class="mt-3">
                <div class="card card-warning">
                    <div class="card-header">
                        <h3 class="card-title">هشدار</h3>
                    </div>
                    <div class="card-body">
                        لطفاً قبل از اعمال تغییرات در ویژگی‌های محصول اطمینان حاصل کنید. پس از اعمال تغییرات، قیمت‌ها به مقدار ۰ تغییر خواهند کرد. لطفاً قیمت‌ها را مجدداً بررسی و تنظیم نمایید.
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

ShahrChap.Web/Pages/Admin/Products/DeleteProduct.cshtml
@page "{id}"
@using ShahrChap.Core.Convertors
@model ShahrChap.Web.Pages.Admin.Products.DeleteProductModel
@{
    ViewData["Title"] = "- حذف محصول";
}

<div class="container mt-4">
    <div class="row mb-3">
        <div class="col-md-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb p-2 rounded-3">
                    <li class="breadcrumb-item"><a href="/Admin"><i class="uil uil-estate"></i> صفحه نخست</a></li>
                    <li class="breadcrumb-item"><a href="/Admin/Products"><i class="uil uil-list-ul"></i> لیست محصولات</a></li>
                    <li class="breadcrumb-item active text-danger" aria-current="page"><i class="uil uil-trash-alt"></i> حذف @Model.Product.ProductTitle</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="card border-danger shadow-lg">
        <div class="card-header bg-danger text-white">
            <h5 class="mb-0"><i class="uil uil-exclamation-triangle"></i> حذف محصول "@Model.Product.ProductTitle"</h5>
        </div>
        <div class="card-body text-center">
            <p class="text-muted">آیا از حذف محصول زیر مطمئن هستید؟</p>
            <div class="d-flex justify-content-center">
                <img src="~/product/thumb/@Model.Product.Image" class="img-thumbnail shadow-sm" style="max-width: 200px; border-radius: 10px;" />
            </div>
            <p class="mt-3 text-secondary">@FixText.GetPlainText(Model.Product.Description)</p>

        </div>
        <div class="card-footer d-flex justify-content-between">
            @if (Model.Product.ParentId != null)
            {
                <a href="/Admin/Products/IndexSubProduct/@Model.Product.ParentId" class="btn btn-light border"><i class="uil uil-angle-right"></i> بازگشت</a>
            }
            else
            {
                <a href="/Admin/Products" class="btn btn-light border"><i class="uil uil-angle-right"></i> بازگشت</a>
            }

            <form method="post">
                <input type="hidden" asp-for="Product.ProductId" />
                <button type="submit" class="btn btn-danger"><i class="uil uil-trash-alt"></i> حذف</button>
            </form>
        </div>
    </div>
</div>